# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic
from typing import Any, List, Optional


class Review(pydantic.BaseModel):
    id: int
    pkey: str
    rating: int
    comment: Optional[str]
    user_hash: Optional[str]
    created_at: datetime.datetime


class Syllabus(pydantic.BaseModel):
    pkey: str
    title: str
    title_en: Optional[str]
    year: int
    semester: str
    credits: Optional[int]
    department: Optional[str]
    instructors: List[str]
    description: Optional[str]
    objectives: Optional[str]
    schedule: Optional[Any]
    evaluation: Optional[str]
    textbooks: Optional[str]
    search_vector: Optional[Any]
    raw_html: Optional[str]
    crawled_at: datetime.datetime
    updated_at: Optional[datetime.datetime]
